feat: add cocogitto/cocogitto
[cocogitto/cocogitto](https://github.com/cocogitto/cocogitto): The Conventional Commits toolbox

```console
$ aqua g -i cocogitto/cocogitto
```

Reviewers aren't necessarily familiar with this package, so please describe how to confirm if this package works well.
Please confirm if this package works well yourself as much as possible.

Command and output

```console
$ cog verify 'chore(commit-msg): test cocogitto'
test cocogitto (not committed) - now
        Author: hituzi no sippo
        Type: chore
        Scope: commit-msg

$ cog verify 'test cocogitto'
Error: Missing commit type separator `:`

Caused by:
     --> 1:5
      |
    1 | test cocogitto
      |     ^---
      |
      = expected scope or type_separator

```

If files such as configuration file are needed, please share them.

None

Reference

- https://github.com/cocogitto/cocogitto/releases/tag/5.2.0
- http://cocogitto.io/